name: eleanor
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  go_router: ^14.8.1
  http: ^1.2.1
  webview_flutter: ^4.7.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.4
  permission_handler: ^11.3.0

  flutter_dotenv: ^5.1.0
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  device_info_plus: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/food-journal.jpg
    - assets/media-library.jpg
    - assets/groceries.jpg
